from fastapi import FastAPI
from pydantic import BaseModel

#define task class user input
class Task(BaseModel):
    title: str
    completed: bool
    #id is not provided by user, but generated by program

#task data
tasks = [
    {
        "id": 1,
        "title": "Learn FastAPI",
        "completed": False
    },
    {
        "id": 2,
        "title": "Create endpoints",
        "completed": False
    }
]

#initial app
global currentID
currentID = 2
app = FastAPI()


#home page endpoint
@app.get("/")
def root():
    return {"message": "Task tracker backend running"}


#get tasks endpoint
@app.get("/tasks")
def get_tasks():
    return tasks

#create task endpoint
@app.post("/tasks")
def create_task(task: Task):
    global currentID
    currentID = currentID + 1
    id = currentID
    title = task.title
    completed = task.completed
    new_task = {
        "id": id,
        "title": title,
        "completed": completed
    }
    tasks.append(new_task)

