from fastapi import FastAPI
from pydantic import BaseModel

#define task class (client input)
class Task(BaseModel):
    title: str
    completed: bool
    #id is not provided by user, it is generated by server

#task data
tasks = [
    {
        "id": 1,
        "title": "Learn FastAPI",
        "completed": False
    },
    {
        "id": 2,
        "title": "Create endpoints",
        "completed": False
    }
]

#initial app
global currentID
currentID = 2
app = FastAPI()


#home page endpoint
@app.get("/")
def home():
    return {"message": "Task tracker backend running"}


#get tasks endpoint
@app.get("/tasks")
def get_tasks():
    return tasks

#create task endpoint
@app.post("/tasks")
def create_task(task: Task):
    global currentID
    currentID = currentID + 1
    id = currentID
    title = task.title
    completed = task.completed
    new_task = {
        "id": id,
        "title": title,
        "completed": completed
    }
    tasks.append(new_task)

#get single task endpoint
@app.get("/tasks/{id}")
def get_one_task(id: int):
    for x in tasks:
        if x["id"] == id:
            return x
        
    #id not found
    return {"message": "A task with that ID does not exist"}



