from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, Boolean
from database import Base

#Pydantic task class (client input)
class Task(BaseModel):
    title: str
    completed: bool
    #id is not provided by user, it is generated by server

#database task class (server side)
class TaskDB(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    completed = Column(Boolean, default=False, nullable=False)