from pydantic import BaseModel, field_validator
from sqlalchemy import Column, Integer, String, Boolean
from database import Base

#Pydantic task class (client input)
class Task(BaseModel):
    title: str
    completed: bool
    #id is not provided by user, it is generated by server

    #input validation for title field
    @field_validator('title')
    @classmethod
    def validate_title(cls, v):
        if not v or not v.strip():
            raise ValueError('Title cannot be empty')
        if len(v.strip()) > 100:
            raise ValueError('Title cannot exceed 100 characters')
        return v.strip()

#database task class (server side)
class TaskDB(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    completed = Column(Boolean, default=False, nullable=False)

    #define a string representation for the TaskDB class
    def __repr__(self):
        return f"TaskDB(id={self.id}, title='{self.title}', completed={self.completed})"